name: tw_wallet_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.10.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_mobx: ^2.0.4
  flutter_secure_storage: ^4.2.0
  mobx: ^2.0.5
  pin_code_fields: ^6.0.2
  random_string: ^2.0.1
  encrypt: ^5.0.0
  fluro: ^1.3.4
  decimal: ^0.3.5
  dio: ^4.0.4
  bip32: ^1.0.5
  bip39: ^1.0.3
  ethereum_address: ^1.0.0
  validators: ^3.0.0
  cached_network_image: ^3.2.0
  optional: ^5.0.0
  json_store: ^2.0.0-nullsafety.0
  more: ^2.5.0
  uuid: ^3.0.6
  date_format: ^1.0.9
  web3dart: ^2.3.5
  http: ^0.13.4
  built_value: ^8.1.4
  built_value_generator: ^8.1.4
  built_collection: ^5.1.1
  mockito: ^5.1.0
  flutter_custom_dialog: ^1.0.19
  qr_flutter: ^3.2.0
  ai_barcode: ^1.1.4
  permission_handler: ^5.0.0+hotfix.5
  flushbar: ^1.10.2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  custom_radio_grouped_button: ^1.0.0
  convert: ^2.1.1
  package_info: ^0.4.0+18
  device_info: ^1.0.0
  get: ^4.6.1
  intl: ^0.16.1
  webview_flutter: ^1.0.7
  sentry: ^4.0.1
  crypto: ^2.1.5
  flutter_native_splash: ^2.0.5
  corsac_jwt: ^1.0.0-nullsafety.1
  path_provider: ^1.6.27
  flutter_webview_plugin: ^0.4.0
  collection: ^1.14.13
  flutter_ble_lib: ^2.3.2
  crypton: ^2.0.3
  search_choices: ^1.0.17
  connectivity: ^2.0.2
  quick_log: ^2.0.0
  flutter_blue: ^0.8.0
  duration: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5
  json_serializable: ^6.1.4
  lint: ^1.2.0

dependency_overrides:
  pointycastle: ^3.5.1
  crypto: ^3.0.0
  convert: ^3.0.0
  logging: ^1.0.0
  args: ^2.3.0
  path_provider: ^2.0.9
  sqflite: ^2.0.0+3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: PingFangHK
      fonts:
        - asset: assets/fonts/PingFang.ttc
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/icons/dapp/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flutter_native_splash:
  image: assets/images/t-wallet.png
  color: "#ffffff"
